/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AppUsersProfile;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Patient.VitalSign;
import Business.UserAccount.UserAccount;
import UserInterface.AppUsersProfile.Activities.ActivitiesWorkAreaJPanel;
import UserInterface.AppUsersProfile.AppUserConsulting.AppUserConsultingJPanel;
import UserInterface.AppUsersProfile.DetailAnalysis.DetailAnalysisJPanel;
import UserInterface.AppUsersProfile.FinancialAdvice.AppUserFinancialAdviceJPanel;
import UserInterface.AppUsersProfile.ProfileView.ProfileViewWorkAreaJPanel;
import UserInterface.AppUsersProfile.Setup.SetupWorkAreaJPanel;
import UserInterface.AppUsersProfile.Setup.SyncDeviceJPanel;
import com.alee.extended.panel.CenterPanel;
import com.alee.extended.panel.GroupPanel;
import com.alee.laf.button.WebButton;
import com.alee.managers.notification.NotificationIcon;
import com.alee.managers.notification.NotificationManager;
import com.alee.managers.notification.WebNotification;
import java.awt.CardLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.concurrent.ExecutionException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingWorker;

/**
 *
 * @author Zak
 */
public class AppUsersWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Enterprise enterprise;
    public static SwingWorker<Boolean, Void> worker;
   
    /**
     * Creates new form AppUsersWorkAreaJPanel
     */
    public AppUsersWorkAreaJPanel(JPanel upc, EcoSystem e, UserAccount ua, Enterprise en) {
        initComponents();
        userProcessContainer = upc;
        business = e;
        enterprise = en;
        userAccount = ua;
        nameLabel.setText("Hey " + userAccount.getEmployee().getName());
        try {
            photoLinkLabel.setIcon(resizing(ua.getEmployee().getPhotoLink()));
        } catch (IOException ex) {
        }
        try {
            jLabel3.setText("");
            jLabel3.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(("/images/smartYOU.jpg"))).getScaledInstance(200, 150, Image.SCALE_SMOOTH)));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Image cannot be loaded");
        }
        ThreadCreation();
    }

    public Icon resizing(String filepath) throws IOException {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(filepath));
        } catch (IOException e) {
            img=ImageIO.read(getClass().getResource("/images/DefaultProfilePhoto.png"));
        }
        Image dimg = img.getScaledInstance(150, 150, Image.SCALE_SMOOTH);
        return (new javax.swing.ImageIcon(dimg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        photoLinkLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnActivities = new javax.swing.JButton();
        btnDetailAnalysis = new javax.swing.JButton();
        btnDoctorConsultation = new javax.swing.JButton();
        btnFinancialAdvices = new javax.swing.JButton();
        btnSetup = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnProfileView = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1025, 682));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        nameLabel.setText("jLabel2");

        photoLinkLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        photoLinkLabel.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabel3.setText("jLabel3");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("My Menu"));

        btnActivities.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnActivities.setText("Activities");
        btnActivities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivitiesActionPerformed(evt);
            }
        });

        btnDetailAnalysis.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnDetailAnalysis.setText("Detail Analysis");
        btnDetailAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailAnalysisActionPerformed(evt);
            }
        });

        btnDoctorConsultation.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnDoctorConsultation.setText("Doctor Consultation");
        btnDoctorConsultation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorConsultationActionPerformed(evt);
            }
        });

        btnFinancialAdvices.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnFinancialAdvices.setText("Financial Advices");
        btnFinancialAdvices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinancialAdvicesActionPerformed(evt);
            }
        });

        btnSetup.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnSetup.setText("Setup");
        btnSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActivities, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinancialAdvices, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoctorConsultation, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetailAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnSetup)
                .addGap(27, 27, 27)
                .addComponent(btnActivities)
                .addGap(27, 27, 27)
                .addComponent(btnFinancialAdvices)
                .addGap(27, 27, 27)
                .addComponent(btnDoctorConsultation)
                .addGap(27, 27, 27)
                .addComponent(btnDetailAnalysis)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        btnProfileView.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnProfileView.setText("Profile View");
        btnProfileView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProfileView, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnProfileView)
                .addGap(46, 46, 46))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("<html>Welcome to <i style=color:red>smart YOU</i></html>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(467, 467, 467))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(photoLinkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(nameLabel)
                                .addGap(5, 5, 5)
                                .addComponent(photoLinkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(210, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void ThreadCreation() {
        //notification1 = btnNotifcation;
        Thread t1 = null;
        worker = new SwingWorker<Boolean, Void>() {
            @Override
            protected Boolean doInBackground() throws Exception {
                // Simulate doing something useful.
                for (int i = 0; i <= 100; i++) {
                    t1.sleep(10000);
                    notifyManager();
                }
                return true;
            }

            // Can safely update the GUI from this method.
            protected void done() {

                boolean status;
                try {

                    // Retrieve the return value of doInBackground.
                    status = get();
                } catch (InterruptedException e) {
                    // This is thrown if the thread's interrupted.
                } catch (ExecutionException e) {
                }
            }
        };
        worker.execute();
    }

    public void notifyManager() throws InterruptedException {
        final WebNotification notificationPopup = new WebNotification();
        notificationPopup.setIcon(NotificationIcon.question);
        final JLabel label = new JLabel("Please Log your Vital Signs");
        final WebButton button1 = new WebButton("Log Now");
        final WebButton button2 = new WebButton("Later");
        button1.setRolloverDecoratedOnly(true);
        button1.setDrawFocus(false);
        button1.setLeftRightSpacing(0);
        button1.setBoldFont();
        button2.setRolloverDecoratedOnly(true);
        button2.setDrawFocus(false);
        button2.setLeftRightSpacing(0);
        button2.setBoldFont();
        button1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(final ActionEvent e) {
                SyncDeviceJPanel syncDeviceJPanel = new SyncDeviceJPanel(userProcessContainer, userAccount);
                userProcessContainer.add("syncDevicesJPanel", syncDeviceJPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        });
        button2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(final ActionEvent e) {
                float respiratoryRate = idealRespiratoryRate();
                float heartRate = idealHeartRate();
                float bloodPressure = idealBloodPressure();
                float temperature = idealTemperature();
                VitalSign vital = userAccount.getPatient().getVitalSignHistory().addVitalSign(respiratoryRate, heartRate, bloodPressure, temperature);
                notificationPopup.hidePopup();
            }
        });
        final CenterPanel centerPanel = new CenterPanel(button1, false, true);
        final CenterPanel centerPanel2 = new CenterPanel(button2, false, true);

        notificationPopup.setContent(new GroupPanel(2, label, centerPanel, centerPanel2));
        NotificationManager.showNotification(notificationPopup);
        Thread t2 = null; //new Thread((Runnable) notificationPopup);
        t2.sleep(5000);
        notificationPopup.hidePopup();
    }

    public float idealRespiratoryRate() {
        return (float) (16 + Math.random() * (20 - 16));
    }

    public float idealHeartRate() {
        return (float) (100 + Math.random() * (170 - 100));
    }

    public float idealBloodPressure() {
        return (float) (90 + Math.random() * (120 - 90));
    }

    public float idealTemperature() {
        return (float) (96 + Math.random() * (99 - 96));
    }


    private void btnSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetupActionPerformed
        // TODO add your handling code here:
        SetupWorkAreaJPanel setupWorkAreaJPanel = new SetupWorkAreaJPanel(userProcessContainer, business, userAccount, enterprise);
        userProcessContainer.add("setupWorkAreaJPanel", setupWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSetupActionPerformed

    private void btnActivitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivitiesActionPerformed
        // TODO add your handling code here:
        if (userAccount.getApplianceDirectory().getApplianceList().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please setup the appliances before using this feature.");
            return;
        }
         if (userAccount.getInvestor().getFinancialsDirectory().getFinancialsList().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please setup the financials before using this feature.");
            return;
        }
        ActivitiesWorkAreaJPanel activitiesWorkAreaJPanel = new ActivitiesWorkAreaJPanel(userProcessContainer, userAccount, enterprise);
        userProcessContainer.add("activitiesWorkAreaJPanel", activitiesWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnActivitiesActionPerformed

    private void btnProfileViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileViewActionPerformed
        // TODO add your handling code here:
        if (userAccount.getApplianceDirectory().getApplianceList().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please setup the appliances before using this feature.");
            return;
        }
         if (userAccount.getInvestor().getFinancialsDirectory().getFinancialsList().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please setup the financials before using this feature.");
            return;
        }
         if (userAccount.getPatient().getVitalSignHistory().getVitalSignList().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please log the vitals signs before using this feature.");
            return;
        }
        ProfileViewWorkAreaJPanel profileViewWorkAreaJPanel = new ProfileViewWorkAreaJPanel(userProcessContainer, business, userAccount);
        userProcessContainer.add("profileViewWorkAreaJPanel", profileViewWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProfileViewActionPerformed

    private void btnDetailAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailAnalysisActionPerformed
        // TODO add your handling code here:
        if (userAccount.getApplianceDirectory().getApplianceList().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please setup the appliances before using this feature.");
            return;
        }
         if (userAccount.getInvestor().getFinancialsDirectory().getFinancialsList().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please setup the financials before using this feature.");
            return;
        }
         if (userAccount.getPatient().getVitalSignHistory().getVitalSignList().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please log the vitals signs before using this feature.");
            return;
        }
        DetailAnalysisJPanel detailAnalysisJPanel = new DetailAnalysisJPanel(userProcessContainer, business,userAccount);
        userProcessContainer.add("detailAnalysisJPanel", detailAnalysisJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDetailAnalysisActionPerformed

    private void btnDoctorConsultationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorConsultationActionPerformed
        // TODO add your handling code here:
        AppUserConsultingJPanel appUserConsultingJPanel = new AppUserConsultingJPanel(userProcessContainer, userAccount);
        userProcessContainer.add("AppUserConsultingJPanel", appUserConsultingJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDoctorConsultationActionPerformed

    private void btnFinancialAdvicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinancialAdvicesActionPerformed
        // TODO add your handling code here:
        AppUserFinancialAdviceJPanel appUserFinancialAdviceJPanel = new AppUserFinancialAdviceJPanel(userProcessContainer, userAccount);
        userProcessContainer.add("appUserFinancialAdviceJPanel", appUserFinancialAdviceJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnFinancialAdvicesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivities;
    private javax.swing.JButton btnDetailAnalysis;
    private javax.swing.JButton btnDoctorConsultation;
    private javax.swing.JButton btnFinancialAdvices;
    private javax.swing.JButton btnProfileView;
    private javax.swing.JButton btnSetup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel photoLinkLabel;
    // End of variables declaration//GEN-END:variables
}
