/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AppUsersProfile.Activities;

import Business.Enterprise.Enterprise;
import Business.Investor.Financials;
import Business.Organization.FinancialAdvisorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.TransactionWorkRequest;
import com.alee.extended.panel.SingleAlignPanel;
import com.alee.extended.window.PopOverDirection;
import com.alee.extended.window.WebPopOver;
import com.alee.laf.button.WebButton;
import com.alee.laf.label.WebLabel;
import java.awt.CardLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class FinancialTransactionJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private WebPopOver webPopOver;

    /**
     * Creates new form RequestLabTestJPanel
     */
    public FinancialTransactionJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, String msg) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        activityTextField.setText(msg);
        webPopOver = new WebPopOver();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        activityTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        btnPerformActivity = new com.alee.laf.button.WebButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        debitAmountTextField = new javax.swing.JFormattedTextField();
        creditAmountTextField = new javax.swing.JFormattedTextField();
        creditLimitTextField = new javax.swing.JFormattedTextField();

        setPreferredSize(new java.awt.Dimension(1025, 682));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setText("Message");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 25));

        activityTextField.setEditable(false);
        activityTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        activityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activityTextFieldActionPerformed(evt);
            }
        });

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        btnPerformActivity.setText("Capture a Transaction");
        btnPerformActivity.setPreferredSize(new java.awt.Dimension(200, 25));
        btnPerformActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformActivityActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setText("Credit Limit");
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Transaction");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Debit Amount");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("Credit Amount");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 25));

        debitAmountTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#####.###"))));
        debitAmountTextField.setPreferredSize(new java.awt.Dimension(200, 25));

        creditAmountTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#####.###"))));
        creditAmountTextField.setPreferredSize(new java.awt.Dimension(200, 25));

        creditLimitTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#####.###"))));
        creditLimitTextField.setPreferredSize(new java.awt.Dimension(200, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(activityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(debitAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(creditAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(creditLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPerformActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(backJButton)))
                .addGap(387, 387, 387))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel5)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(activityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(debitAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(creditAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(creditLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(btnPerformActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(backJButton)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closePopOverDialogs() {

        webPopOver.dispose();

    }

    private WebPopOver createPopOver() {
        final WebPopOver popOver = new WebPopOver(this);
        popOver.setMargin(10);
        popOver.setFocusableWindowState(false);
        //GridLayout grid = new GridLayout(userAccount.getInvestor().getFinancialsDirectory().getFinancialsList().size(), 1);
        GridLayout grid = new GridLayout(4, 1);
        popOver.setLayout(grid);
        popOver.add(new WebLabel("Financial Activity is " + activityTextField.getText()), grid);
        popOver.add(new WebLabel("Debit Profile" + ": " + userAccount.getInvestor().getDebitProfile()), grid);
        popOver.add(new WebLabel("Create Profile" + ": " + userAccount.getInvestor().getCreditProfile()), grid);
        popOver.add(new SingleAlignPanel(new WebButton("Close pop-over", new ActionListener() {
            @Override
            public void actionPerformed(final ActionEvent e) {
                popOver.dispose();
            }
        }), SingleAlignPanel.RIGHT).setMargin(10, 0, 0, 0));

        popOver.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(final WindowEvent e) {
                webPopOver.remove(popOver);
            }
        });
        return popOver;
    }

    public boolean ChangeDebitCreditProfile() {
        double bankBal = userAccount.getInvestor().getDebitProfile();
        double creditBal = userAccount.getInvestor().getCreditProfile();
        double credit = Double.parseDouble(creditAmountTextField.getText());
        double debit = Double.parseDouble(debitAmountTextField.getText());
        double creditBilling = Double.parseDouble(creditLimitTextField.getText());
        double newdebitBal = bankBal - debit + credit;
        double newcreditBal = creditBal - creditBilling;
        if (((newdebitBal) < 0) || ((newcreditBal) < 0)) {
            return false;
        } else {
            userAccount.getInvestor().setDebitProfile(newdebitBal);
            userAccount.getInvestor().setCreditProfile(newcreditBal);
            return true;
        }

    }

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void activityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activityTextFieldActionPerformed

    private void btnPerformActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformActivityActionPerformed
        // TODO add your handling code here:
        String message = activityTextField.getText();
        String creditAmount = creditAmountTextField.getText();
        String debitAmount = debitAmountTextField.getText();
        String creditBalance = creditLimitTextField.getText();
        if (creditAmount.equalsIgnoreCase("") || debitAmount.equalsIgnoreCase("") || creditBalance.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Please add the details first");
            return;
        }
        if (ChangeDebitCreditProfile()) {

            TransactionWorkRequest request = new TransactionWorkRequest();
            request.setMessage(message);
            request.setRequestType("Financial Transaction");
            request.setSender(userAccount);
            request.setStatus("Sent");
            request.setCreditAmount(Float.parseFloat(creditAmountTextField.getText()));
            request.setDebitAmount(Float.parseFloat(debitAmountTextField.getText()));
            request.setCreditBilling(Double.parseDouble(creditLimitTextField.getText()));
            request.setTxnTimeStamp(new Date());
            request.setTransactionID(String.valueOf((100000000 + Math.random() * (9999999 - 1000000))));
            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof FinancialAdvisorOrganization) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
            try {
                webPopOver.add(createPopOver().show(btnPerformActivity, PopOverDirection.up));
            } catch (Exception e) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "You cannot proceed with the following Transaction" + "\n" + "Debit Profile:" + userAccount.getInvestor().getDebitProfile() + "\n" + "Credit Profile:" + userAccount.getInvestor().getCreditProfile());
        }
    }//GEN-LAST:event_btnPerformActivityActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField activityTextField;
    private javax.swing.JButton backJButton;
    private com.alee.laf.button.WebButton btnPerformActivity;
    private javax.swing.JFormattedTextField creditAmountTextField;
    private javax.swing.JFormattedTextField creditLimitTextField;
    private javax.swing.JFormattedTextField debitAmountTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
