/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FinancialAdvisorProfile;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.FinancialAdviceWorkRequest;
import Business.WorkRequest.WorkQueue;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Zak
 */
public class AdviceJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private WorkQueue workQueue;
    private UserAccount financialAdvisorUserAccount;
    private UserAccount investorUserAccount;
    private Enterprise enterprise;

    /**
     * Creates new form ActivitiesJPanel
     */
    public AdviceJPanel(JPanel upc, UserAccount faua, UserAccount iua, WorkQueue wq) {
        initComponents();
        userProcessContainer = upc;
        financialAdvisorUserAccount = faua;
        investorUserAccount = iua;
        workQueue = wq;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSendToInvestor = new com.alee.laf.button.WebButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        financialAdvicingTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        subjectTextField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1025, 682));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Financial Advicing");

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Subject");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 20));

        btnSendToInvestor.setText("Send To Investor");
        btnSendToInvestor.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnSendToInvestor.setPreferredSize(new java.awt.Dimension(200, 25));
        btnSendToInvestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToInvestorActionPerformed(evt);
            }
        });

        financialAdvicingTextArea.setColumns(20);
        financialAdvicingTextArea.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        financialAdvicingTextArea.setLineWrap(true);
        financialAdvicingTextArea.setRows(5);
        financialAdvicingTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(financialAdvicingTextArea);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("Financial Advicing");
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 20));

        subjectTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(subjectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSendToInvestor, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel1)))
                .addGap(397, 397, 397))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(btnSendToInvestor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnBack)
                .addGap(202, 202, 202))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSendToInvestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToInvestorActionPerformed
        // TODO add your handling code here:
        String message = subjectTextField.getText().replaceAll("^\\s+|\\s+$", "");
        String financialAdv = financialAdvicingTextArea.getText().replaceAll("^\\s+|\\s+$", "");
        
        if (message.equalsIgnoreCase("") || financialAdv.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Please fill in the details first");
            return;
        }
        FinancialAdviceWorkRequest request = new FinancialAdviceWorkRequest();
        request.setMessage(message);
        request.setRequestType("Financial Advice");
        request.setAdviceDescription(financialAdv);
        request.setSender(financialAdvisorUserAccount);
        request.setReceiver(investorUserAccount);
        request.setStatus("Sent");
        request.setRequestDate(new Date());
        investorUserAccount.getWorkQueue().getWorkRequestList().add(request);
        financialAdvisorUserAccount.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "Financial Advice sent to the Investor");
    }//GEN-LAST:event_btnSendToInvestorActionPerformed

    private void subjectTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private com.alee.laf.button.WebButton btnSendToInvestor;
    private javax.swing.JTextArea financialAdvicingTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField subjectTextField;
    // End of variables declaration//GEN-END:variables
}
