/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AppUsersProfile.Setup;

import Business.Patient.Patient;
import Business.Patient.VitalSign;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Zak
 */
public class SyncDeviceJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;

    /**
     * Creates new form AppUsersWorkAreaJPanel
     */
    public SyncDeviceJPanel(JPanel upc, UserAccount ua) {
        initComponents();
        userProcessContainer = upc;
        userAccount = ua;
    }

    public void restrictNumericinTxtFields(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        JTextField jt = (JTextField) evt.getSource();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            jt.setText("");
            jt.setBackground(Color.red);
            evt.consume();

        } else {
            jt.setBackground(Color.white);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddVitalSign = new javax.swing.JButton();
        heartRateJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        respiratoryRateJTextField = new javax.swing.JTextField();
        bloodPressureJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        temperatureJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1025, 682));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setText("Heart Rate");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 25));

        btnAddVitalSign.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnAddVitalSign.setText("Add Vital Sign");
        btnAddVitalSign.setPreferredSize(new java.awt.Dimension(200, 25));
        btnAddVitalSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVitalSignActionPerformed(evt);
            }
        });

        heartRateJTextField.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        heartRateJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        heartRateJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                heartRateJTextFieldKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setText("Respiratory Rate");
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 25));

        respiratoryRateJTextField.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        respiratoryRateJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        respiratoryRateJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                respiratoryRateJTextFieldKeyTyped(evt);
            }
        });

        bloodPressureJTextField.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        bloodPressureJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        bloodPressureJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bloodPressureJTextFieldKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel7.setText("Blood Pressure");
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 25));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Temperature");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 25));

        temperatureJTextField.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        temperatureJTextField.setPreferredSize(new java.awt.Dimension(200, 25));
        temperatureJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                temperatureJTextFieldKeyTyped(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Vital Sign Manual Log");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bloodPressureJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(respiratoryRateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(heartRateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(temperatureJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddVitalSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(271, 271, 271))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel3)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bloodPressureJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(respiratoryRateJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(heartRateJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperatureJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnAddVitalSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(backJButton)
                .addGap(159, 159, 159))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddVitalSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVitalSignActionPerformed
        if (bloodPressureJTextField.getText().isEmpty() || respiratoryRateJTextField.getText().isEmpty() || heartRateJTextField.getText().isEmpty()
                || temperatureJTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the details first.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Patient patient = userAccount.getPatient();
        VitalSign vitalsign = patient.getVitalSignHistory().addVitalSign();
        vitalsign.setBloodPressure(Float.parseFloat(bloodPressureJTextField.getText()));
        vitalsign.setRespiratoryRate(Float.parseFloat(respiratoryRateJTextField.getText()));
        vitalsign.setHeartRate(Float.parseFloat(heartRateJTextField.getText()));
        vitalsign.setTemperature(Float.parseFloat(temperatureJTextField.getText()));
        vitalsign.setTimestamp(new Date());
        JOptionPane.showMessageDialog(null, "Vital SIgn has been recoreded for the patient");
    }//GEN-LAST:event_btnAddVitalSignActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void bloodPressureJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bloodPressureJTextFieldKeyTyped
        // TODO add your handling code here:
        restrictNumericinTxtFields(evt);
    }//GEN-LAST:event_bloodPressureJTextFieldKeyTyped

    private void respiratoryRateJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_respiratoryRateJTextFieldKeyTyped
        // TODO add your handling code here:
        restrictNumericinTxtFields(evt);
    }//GEN-LAST:event_respiratoryRateJTextFieldKeyTyped

    private void heartRateJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heartRateJTextFieldKeyTyped
        // TODO add your handling code here:
        restrictNumericinTxtFields(evt);
    }//GEN-LAST:event_heartRateJTextFieldKeyTyped

    private void temperatureJTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_temperatureJTextFieldKeyTyped
        // TODO add your handling code here:
        restrictNumericinTxtFields(evt);
    }//GEN-LAST:event_temperatureJTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField bloodPressureJTextField;
    private javax.swing.JButton btnAddVitalSign;
    private javax.swing.JTextField heartRateJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField respiratoryRateJTextField;
    private javax.swing.JTextField temperatureJTextField;
    // End of variables declaration//GEN-END:variables
}
